# Site settings
title: Programiranje u oblaku
email: nastavnik.vlkn@gmail.com
url: https://vulkanznanje.github.io/
description: "Nastava programiranja u oblaku: paradigma novog doba. Obuka za nastavnike akreditovana kod ZUOV-a (kataloški broj 376). Organizator: Vulkan znanje. Autori: Miloš Papić, Dalibor Čukljević, Zoran Luković."
keywords: "Github, Markdown, Github Page, Jupyter Notebook, Jupyter Lab, Jupyter Lite, Google Colab"
skills: "Miloš Papić - Dalibor Čukljević - Zoran Luković"
meta_author: Čukljević Dalibor


# Team names, titles and social links
people:
- name: Miloš Papić
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Dalibor Čukljević
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Zoran Luković
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll 
  location: Organizator
  social: POSETITE I...
  credits: OD ISTIH AUTORA

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/vulkanznanje/fajlovi
  - title: github
    url: https://vulkanznanje.github.io/
  - title: youtube
    url: https://www.youtube.com/@vulkanznanjeInformatika
  - title: instagram
    url: https://www.instagram.com/vulkan_znanje/
  - title: facebook
    url: https://www.facebook.com/vulkanznanje/



# Postal address (add as many lines as necessary)
address:
  - line: Vulkan znanje 
  - line: Gospodara Vučića 245, Beograd

# Credits content
credits: '<a href="https://sites.google.com/view/moderneprezentacije">Statičke i dinamičke prezentacije u svetlu novih tehnologija</a> (kataloški broj <a href="https://zuov-katalog.rs/index.php?action=page/catalog/view&id=857">393</a>).'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
